name: detectron
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - tqdm
  - numpy
  - scipy
  - pandas
  - pillow
  - pytorch
  - matplotlib
  - torchvision
  - scikit-learn
  - pip
  - pip:
    - Pillow
    - scikit-image
    - opencv-python
